### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by mazhengyufreedom** [arrival-ltd/catalyst-rl-tutorial#11]
When {CUDA_VISIBLE_DEVICES='0' catalyst-rl run-trainer --config configs/config.yml} is executed during run-training.sh, catalyst.utils.tools.registry.RegistryException: No factory with name 'CoppeliaSimEnvWrapper' was registered

what is the problem and which version of catalyst should I use?

Traceback (most recent call last):
  File "/workspace/mazhengyu/anaconda3/envs/catalystenv/bin/catalyst-rl", line 8, in <module>
    sys.exit(main())
  File "/workspace/mazhengyu/anaconda3/envs/catalystenv/lib/python3.6/site-packages/catalyst/rl/__main__.py", line 44, in main
    COMMANDS[args.command].main(args, uargs)
  File "/workspace/mazhengyu/anaconda3/envs/catalystenv/lib/python3.6/site-packages/catalyst/rl/scripts/run_trainer.py", line 69, in main
    env = ENVIRONMENTS.get_from_params(**config["environment"])
  File "/workspace/mazhengyu/anaconda3/envs/catalystenv/lib/python3.6/site-packages/catalyst/utils/tools/registry.py", line 244, in get_from_params
    return self.get_instance(name, meta_factory=meta_factory, **kwargs)
  File "/workspace/mazhengyu/anaconda3/envs/catalystenv/lib/python3.6/site-packages/catalyst/utils/tools/registry.py", line 216, in get_instance
    f = self.get(name)
  File "/workspace/mazhengyu/anaconda3/envs/catalystenv/lib/python3.6/site-packages/catalyst/utils/tools/registry.py", line 187, in get
    f"No factory with name '{name}' was registered"
catalyst.utils.tools.registry.RegistryException: No factory with name 'CoppeliaSimEnvWrapper' was registered

**Comment by xiaobai0906** [comment]
Hi，I have the same problem. Have you resolved it yet？
